name: run-linters
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    container: ghcr.io/evertz-fbrnd/eiosam:latest
    steps:
      - name: pip version
        run: pip --version
      - name: pip freeze
        run: pip freeze
      - name: Checkout
        uses: actions/checkout@v4
      - name: run linters
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{secrets.CODE_ARTIFACT_TOKEN_EVERTZ_IO}}
        run: |
          export NODE_VERSION=16.13.0
          export PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
          export JUNIT_XML_RESULT=$PWD/junit.xml
          export COVERAGE_XML_RESULT=$PWD/coverage.xml
          if [ -f $JUNIT_XML_RESULT ]; then
              \rm $JUNIT_XML_RESULT;
          fi
          export PACKAGE_DIR=cookiecutter
          export SOURCE_TEMPLATE="template.yaml"
          export TEMPLATE_FOLDER="templates"
          export UNIT_TEST_RESULTS="--junitxml=$JUNIT_XML_RESULT --cov-report xml:$COVERAGE_XML_RESULT"

          ./build_scripts/run_linters.sh
      - name: Publish Coverage Report as Comment
        uses: MishaKav/pytest-coverage-comment@v1.1.52
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: junit.xml
          report-only-changed-files: true
          coverage-path-prefix: cookiecutter/
      - name: Add size label
        id: size-label
        uses: 'pascalgn/size-label-action@v0.5.5'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN }}'
          IGNORED: "Pipfile.lock\n**/autogenerated/**"
